[discord.mydiscord]
# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# If you want roles/groups mentions to be shown with names instead of ID, 
# you'll need to give your bot the "Manage Roles" permission.
Token="InsertTokenHere"
Server="Name or uid of the server you are connecting" # picked from guilds the bot is connected to
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[gitter.mygitter]
#You can get your token by going to https://developer.gitter.im/docs/welcome and SIGN IN
Token="InsertTokenHere"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="general"

[[gateway.inout]]
account="gitter.mygitter"
channel="42wim/mygreatproject"

#In the example below RemoteNickFormat we want messages from channel #general on discord to be sent to channel 42wim/mygreatproject on gitter.
#(and messages from channel 42wim/mygreatproject on gitter to channel #general on discord


#Change the Token and Server Keys to the correct ones. 
#Add the gateway configuration to your config file.
#Copy and paste the config from https://github.com/42wim/matterbridge/wiki/Gateway-config-%28basic%29
#Modify the gateway config matching the protocols you selected above.
#For the correct `channel=mychannel` settings, look at
